import futhark
# Importing required headers.
importc:
  # Setting path to clang headers.
  sysPath "/usr/lib/clang/13.0.1/include"
  # We need this argument for opir to pick up on unstable wlroots features.
  compilerArg "-DWLR_USE_UNSTABLE"
  # We set a custom path for headers too, this is where headers generated by wayland-scanner go.
  path "../protocols"
  "wayland-server-core.h" 
  "wayland-server-protocol.h"
  "wayland-server.h"
  "wayland-util.h"
  "wlr/backend.h"
  "wlr/render/allocator.h"
  "wlr/render/wlr_renderer.h"
  "wlr/types/wlr_compositor.h"
  "wlr/types/wlr_cursor.h"
  "wlr/types/wlr_data_device.h"
  "wlr/types/wlr_output.h"
  "wlr/types/wlr_output_layout.h"
  "wlr/types/wlr_scene.h"
  "wlr/types/wlr_seat.h"
  "wlr/types/wlr_xcursor_manager.h"
  "wlr/types/wlr_xdg_shell.h"
  "wlr/util/log.h"

# Re-defining a few type names to match the convention.
type
  wl_display = structwldisplay
  wl_listener = structwllistener
  wl_signal = structwlsignal
  wlr_allocator = structwlrallocator
  wlr_backend = structwlrbackend
  wlr_compositor = structwlrcompositor
  wlr_cursor = structwlrcursor
  wlr_data_device_manager = structwlrdatadevicemanager
  wlr_output = structwlroutput
  wlr_output_layout = structwlroutputlayout
  wlr_renderer = structwlrrenderer
  wlr_scene = structwlrscene
  wlr_seat = structwlrseat
  wlr_xcursor_manager = structwlrxcursormanager
  wlr_xdg_shell = structwlrxdgshell

# Re-defining a inline functions because opir currently does not parse inline functions. This is straight from the header.
proc wl_signal_add(wl_signal: wl_signal, wl_listener: var wl_listener) =
  wl_list_insert(wl_signal.listener_list.prev, unsafeAddr(wl_listener.link));

template fieldParentPtr(T:typedesc, field: untyped, data: pointer): auto =
  cast[ptr T](cast[int](data) - offsetOf(T, field))[]
